import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import Icon from '../components/Icons';
import { PageLoader } from '../components/Ui';
import { money } from '../lib/format';

export function AboutPage() {
  return <><section className="page-banner"><div className="container-wide page-banner-content"><span className="eyebrow">About TaxSaathi</span><h1>Professional service delivery, made more visible.</h1><p>TaxSaathi is a digital tax and compliance service ecosystem with a public catalogue, client portal, document workflow, operational dashboards, and role-aware notifications.</p></div></section><section className="section container-wide two-column-copy"><div><span className="eyebrow">Our approach</span><h2>Clarity is a service feature.</h2><p>The original TaxSaathi platform was built around a simple idea: clients should know what they are buying, what information is required, what happens next, and where their work stands.</p><p>This MERN version preserves that operating model while moving the system to an API-first React interface and MongoDB-compatible data layer.</p></div><div className="feature-stack"><div><span className="mini-icon"><Icon name="shield" size={18} /></span><span><strong>Trustworthy records</strong><small>Orders, payments, documents, and activity stay connected.</small></span></div><div><span className="mini-icon"><Icon name="activity" size={18} /></span><span><strong>Visible progress</strong><small>Status changes and notifications are easy to follow.</small></span></div><div><span className="mini-icon"><Icon name="users" size={18} /></span><span><strong>Role-aware workspaces</strong><small>Clients, staff, executives, and partners see the right tools.</small></span></div></div></section><section className="section light-section"><div className="container-wide values-grid"><div><span className="eyebrow">What is carried forward</span><h2>The experience remains familiar.</h2><p>Services, requirements, invoices, payments, partner orders, notifications, support, tax rules, SEO records, and content settings are all included in the migration path.</p></div><div className="value-card"><strong>57</strong><span>legacy tables mapped</span></div><div className="value-card"><strong>4,773</strong><span>legacy rows available for import</span></div><div className="value-card"><strong>1</strong><span>connected workflow</span></div></div></section></>;
}

export function ContactPage() {
  const [form, setForm] = useState({ name: '', email: '', phone: '', message: '', service: '' }); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setLoading(true); try { const result = await api('/public/contact', { method: 'POST', body: form }); setMessage(result.message); setForm({ name: '', email: '', phone: '', message: '', service: '' }); } catch (error) { setMessage(error.message); } finally { setLoading(false); } }
  return <><section className="page-banner"><div className="container-wide page-banner-content"><span className="eyebrow">Let’s talk</span><h1>Have a question? Start here.</h1><p>Tell us what you need and the TaxSaathi team can guide you to the right service or next step.</p></div></section><section className="section container-wide contact-grid"><div className="contact-copy"><span className="eyebrow">Support and enquiries</span><h2>Make the next conversation useful.</h2><p>Share a little context and your contact details. Your message is recorded in the migrated lead workflow for follow-up.</p><div className="contact-points"><div><span className="mini-icon"><Icon name="phone" size={17} /></span><span><strong>Phone support</strong><small>Use the number configured in website settings.</small></span></div><div><span className="mini-icon"><Icon name="mail" size={17} /></span><span><strong>Email support</strong><small>We’ll follow up with a clear next step.</small></span></div><div><span className="mini-icon"><Icon name="globe" size={17} /></span><span><strong>Guwahati, India</strong><small>Serving clients through a digital-first workflow.</small></span></div></div></div><form className="content-card contact-form" onSubmit={submit}><span className="eyebrow">Send an enquiry</span><h2>Tell us what you need.</h2>{message && <div className="form-message success">{message}</div>}<label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><div className="form-row"><label>Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Phone<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label></div><label>Service or topic<input value={form.service} onChange={(event) => setForm({ ...form, service: event.target.value })} /></label><label>Message<textarea required rows="5" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /></label><button className="button primary" type="submit" disabled={loading}>{loading ? 'Sending…' : 'Send enquiry'} <Icon name="arrow" size={16} /></button></form></section></>;
}

export function CalculatorPage() {
  const [income, setIncome] = useState(''); const [regime, setRegime] = useState('new'); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false);
  async function calculate(event) { event.preventDefault(); setLoading(true); try { setResult(await api('/public/calculators', { method: 'POST', body: { income, regime } })); } finally { setLoading(false); } }
  return <><section className="page-banner"><div className="container-wide page-banner-content"><span className="eyebrow">Tax calculators</span><h1>Estimate before you file.</h1><p>Use the imported tax rules for a quick planning estimate. This is an informational calculation, not a filing assessment.</p></div></section><section className="section container-wide calculator-layout"><form className="calculator-card" onSubmit={calculate}><span className="eyebrow">Quick estimate</span><h2>Calculate estimated tax.</h2><label>Annual taxable income<input type="number" min="0" required value={income} onChange={(event) => setIncome(event.target.value)} placeholder="e.g. 850000" /></label><label>Regime<select value={regime} onChange={(event) => setRegime(event.target.value)}><option value="new">New regime</option><option value="old">Old regime</option></select></label><button className="button primary full" disabled={loading}>{loading ? 'Calculating…' : 'Calculate estimate'} <Icon name="calculator" size={16} /></button><small>Rates and thresholds are read from the migrated tax_rules table.</small></form>{result ? <div className="calculator-result"><span className="eyebrow">Estimated output</span><h2>{money(result.total)}</h2><p>Approximate total including cess for income of {money(result.income)} under the {result.regime} regime.</p><div className="summary-line"><span>Estimated tax</span><strong>{money(result.estimated_tax)}</strong></div><div className="summary-line"><span>Health & education cess</span><strong>{money(result.cess)}</strong></div><Link className="button dark" to="/contact">Talk to a professional <Icon name="arrow" size={16} /></Link></div> : <div className="calculator-placeholder"><Icon name="calculator" size={34} /><h3>Your estimate will appear here.</h3><p>Enter your income and choose a regime to begin.</p></div>}</section></>;
}

export function LegalPage({ title, eyebrow = 'TaxSaathi', text }) {
  return <><section className="page-banner"><div className="container-wide page-banner-content"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>Read the information below before using TaxSaathi services.</p></div></section><section className="section container-wide legal-card"><h2>Our commitment</h2><p>{text || 'TaxSaathi aims to make tax and compliance services clearer, more organized, and easier to follow. Service timelines, requirements, and fees may vary by case and should be confirmed with the service team.'}</p><h3>Service information</h3><p>Published service descriptions and pricing are intended to help you choose a starting point. The final scope may depend on the documents, facts, and information provided by the client.</p><h3>Contact</h3><p>If you need help understanding a service, contact the team before submitting an application.</p></section></>;
}
