import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../components/AuthContext';
import Icon from '../components/Icons';
import { EmptyState, PageIntro, PageLoader } from '../components/Ui';
import { dateLabel } from '../lib/format';

export default function SupportPage() {
  const { user } = useAuth();
  const [conversations, setConversations] = useState(null); const [selected, setSelected] = useState(null); const [messages, setMessages] = useState([]); const [text, setText] = useState(''); const [form, setForm] = useState({ subject: '', message: '' }); const [notice, setNotice] = useState('');
  useEffect(() => { api('/support/conversations').then((payload) => setConversations(payload.conversations || [])).catch(() => setConversations([])); }, []);
  useEffect(() => { if (selected) api(`/support/conversations/${selected.id}/messages`).then((payload) => setMessages(payload.messages || [])).catch(() => setMessages([])); }, [selected]);
  if (!conversations) return <PageLoader label="Loading support…" />;
  async function create(event) { event.preventDefault(); try { const result = await api('/support/conversations', { method: 'POST', body: form }); setConversations((current) => [result.conversation, ...current]); setSelected(result.conversation); setForm({ subject: '', message: '' }); setNotice('Support request created.'); } catch (error) { setNotice(error.message); } }
  async function send(event) { event.preventDefault(); if (!text.trim() || !selected) return; try { const result = await api(`/support/conversations/${selected.id}/messages`, { method: 'POST', body: { message: text } }); setMessages((current) => [...current, result.message]); setText(''); } catch (error) { setNotice(error.message); } }
  return <div className="workspace-page"><PageIntro eyebrow="Support desk" title="Conversations" text="Keep questions, replies, and operational context attached to the right conversation." />{notice && <div className="form-message success">{notice}</div>}<div className="support-layout"><section className="support-list panel"><div className="panel-heading"><h3>Inbox</h3><span className="result-count">{conversations.length}</span></div>{conversations.length ? conversations.map((conversation) => <button className={`conversation-row ${selected?.id === conversation.id ? 'active' : ''}`} key={conversation.id} onClick={() => setSelected(conversation)}><span className="conversation-avatar">{(conversation.requester_name || 'S').slice(0, 1)}</span><span><strong>{conversation.subject}</strong><small>{conversation.last_message_preview || 'No messages yet.'}</small><i>{dateLabel(conversation.last_message_at || conversation.created_at)}</i></span></button>) : <EmptyState icon="support" title="No conversations yet." />}</section><section className="conversation-panel panel">{selected ? <><div className="conversation-header"><div><span className="eyebrow">{selected.public_id || `Conversation #${selected.id}`}</span><h3>{selected.subject}</h3></div><span className="status-badge success"><i />{selected.status || 'open'}</span></div><div className="message-stream">{messages.map((message) => <div className={`chat-bubble ${Number(message.sender_user_id) === Number(user?.id) ? 'mine' : ''}`} key={message.id}><span>{message.sender_name || message.sender_role}</span><p>{message.message}</p><small>{dateLabel(message.created_at)}</small></div>)}{!messages.length && <EmptyState title="No messages yet." text="Send the first message to start the conversation." />}</div><form className="message-compose" onSubmit={send}><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Write a reply…" /><button className="button primary" type="submit"><Icon name="arrow" size={16} /></button></form></> : <div className="new-support"><Icon name="chat" size={34} /><h3>Start a support conversation.</h3><p>Describe what you need and the support team will pick it up from the inbox.</p><form className="content-card" onSubmit={create}><label>Subject<input required value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} /></label><label>Message<textarea required rows="4" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /></label><button className="button dark">Create request <Icon name="arrow" size={16} /></button></form></div>}</section></div></div>;
}
